# Generated by Django 2.2.9 on 2021-08-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vendor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
