# Generated by Django 2.2.9 on 2021-08-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210821_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slots',
            field=models.IntegerField(null=True),
        ),
    ]
