# Generated by Django 2.2.9 on 2021-08-22 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210821_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_vendor',
            new_name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vendor',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.IntegerField(default=100)),
                ('order', models.TextField(blank=True, max_length=250, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
