# Generated by Django 2.2.9 on 2021-08-23 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210822_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_dish', models.CharField(blank=True, choices=[('white rice', 'white rice'), ('fried rice', 'fried rice'), ('mixed rice', 'mixed rice'), ('jollof rice', 'jollof rice'), ('beans', 'beans'), ('spaghetti', 'spaghetti')], max_length=15, null=True)),
                ('main_dish_amount', models.IntegerField(blank=True, null=True)),
                ('toppings', models.CharField(blank=True, choices=[('plantain', 'plantain'), ('moi-moi', 'moi-moi'), ('salad', 'salad')], max_length=15, null=True)),
                ('toppings_amount', models.IntegerField(blank=True, null=True)),
                ('supplements', models.CharField(blank=True, choices=[('meat', 'meat'), ('fish', 'fish'), ('turkey', 'turkey')], max_length=15, null=True)),
                ('supplements_amount', models.IntegerField(blank=True, null=True)),
                ('drinks', models.CharField(blank=True, choices=[('coke', 'coke'), ('fanta', 'fanta'), ('malt', 'malt'), ('sprites', 'sprites')], max_length=15, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
