# Generated by Django 2.2.9 on 2021-08-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210823_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drinks_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
