# Generated by Django 2.2.9 on 2021-08-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210823_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
