# Generated by Django 2.2.9 on 2021-08-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p_o_d',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
