# Generated by Django 2.2.9 on 2021-08-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_p_o_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='main_dish_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='drinks',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='main_dish',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplements',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
