# Generated by Django 2.2.9 on 2021-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210825_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='main_dish_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
