# Generated by Django 2.2.9 on 2021-08-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_main_dish_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
