# Generated by Django 2.2.9 on 2021-08-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210825_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='m_o_p',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
