# Generated by Django 2.2.9 on 2021-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210825_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
