# Generated by Django 2.2.9 on 2021-09-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210826_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='post',
        ),
    ]
