# Generated by Django 2.2.9 on 2021-09-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210904_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='m_o_p',
            new_name='method_of_payment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='p_o_d',
            new_name='place_of_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='buyers_phone_no',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
