# Generated by Django 2.2.9 on 2021-09-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210904_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyers_phone_no',
            new_name='buyer_phone_no',
        ),
    ]
