# Generated by Django 2.2.9 on 2021-09-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
